export enum ConstructionPriority {
    NORMAL = "NORMAL",
    CLOSE_TO_TREE = "CLOSE_TO_TREE",
    CLOSE_TO_MINE = "CLOSE_TO_MINE",
    BETWEEN_MINE_AND_HALL = "BETWEEN_MINE_AND_HALL",
    HALL_AWAY_FROM_MINE = "HALL_AWAY_FROM_MINE",
}