
export enum WorkerOrders {
    ORDER_IDLE = "ORDER_IDLE",
    ORDER_GOLDMINE = "ORDER_GOLDMINE",
    ORDER_WOOD = "ORDER_WOOD",
    ORDER_BUILD = "ORDER_BUILD",
    ORDER_DRAFTED = "ORDER_DRAFTED",
    ORDER_DEAD = "ORDER_DEAD",
}